export const MIN_TARGET_MULTIPLIER = 1.01;
export const MAX_CRASH_MULTIPLIER = 1_000_000;
export const CRASH_MULTIPLIER_DECIMALS = 2;
export const LIMBO_MULTIPLIER_DECIMALS = 2;
export const LIMBO_WIN_CHANCE_DECIMALS = 8;
export const DEFAULT_TARGET_MULTIPLIER = 2;

export const MIN_LIMBO_WIN_CHANCE_PERCENT = 10 ** -LIMBO_WIN_CHANCE_DECIMALS;
export const MAX_LIMBO_WIN_CHANCE_PERCENT = 100 - MIN_LIMBO_WIN_CHANCE_PERCENT;
